version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  server:
    build: ./server
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    ports:
      - '3001:3001'
